chore(deps): update dependency commander to v13 (#1853)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [commander](https://redirect.github.com/tj/commander.js) | [`9.5.0` ->
`13.1.0`](https://renovatebot.com/diffs/npm/commander/9.5.0/13.1.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/commander/13.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/commander/13.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/commander/9.5.0/13.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/commander/9.5.0/13.1.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>tj/commander.js (commander)</summary>

###
[`v13.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1310-2025-01-21)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v13.0.0...v13.1.0)

##### Added

- support a pair of long option flags to allow a memorable shortened
flag, like `.option('--ws, --workspace')`
(\[[#&#8203;2312](https://redirect.github.com/tj/commander.js/issues/2312)])

###
[`v13.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1300-2024-12-30)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v12.1.0...v13.0.0)

##### Added

- support multiple calls to `.parse()` with default settings
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- add `.saveStateBeforeParse()` and `.restoreStateBeforeParse()` for use
by subclasses
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- style routines like `styleTitle()` to add color to help using
`.configureHelp()` or Help subclass
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- color related support in `.configureOutput()` for `getOutHasColors()`,
`getErrHasColors()`, and `stripColor()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help property for `minWidthToWrap`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])
- Help methods for `displayWidth()`, `boxWrap()`, `preformatted()` et al
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Changed

- *Breaking*: excess command-arguments cause an error by default, see
migration tips
(\[[#&#8203;2223](https://redirect.github.com/tj/commander.js/issues/2223)])
- *Breaking*: throw during Option construction for unsupported option
flags, like multiple characters after single `-`
(\[[#&#8203;2270](https://redirect.github.com/tj/commander.js/issues/2270)])
- *Breaking*: throw on multiple calls to `.parse()` if
`storeOptionsAsProperties: true`
(\[[#&#8203;2299](https://redirect.github.com/tj/commander.js/issues/2299)])
- TypeScript: include implicit `this` in parameters for action handler
callback
(\[[#&#8203;2197](https://redirect.github.com/tj/commander.js/issues/2197)])

##### Deleted

- *Breaking*: `Help.wrap()` refactored into `formatItem()` and
`boxWrap()`
(\[[#&#8203;2251](https://redirect.github.com/tj/commander.js/issues/2251)])

##### Migration Tips

**Excess command-arguments**

It is now an error for the user to specify more command-arguments than
are expected. (`allowExcessArguments` is now false by default.)

Old code:

```js
program.option('-p, --port <number>', 'port number');
program.action((options) => {
  console.log(program.args);
});
```

Now shows an error:

```console
$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
```

You can declare the expected arguments. The help will then be more
accurate too. Note that declaring
new arguments will change what is passed to the action handler.

```js
program.option('-p, --port <number>', 'port number');
program.argument('[args...]', 'remote command and arguments'); // expecting zero or more arguments
program.action((args, options) => {
  console.log(args);
});
```

Or you could suppress the error, useful for minimising changes in legacy
code.

```js
program.option('-p, --port', 'port number');
program.allowExcessArguments();
program.action((options) => {
  console.log(program.args);
});
```

###
[`v12.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1210-2024-05-18)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v12.0.0...v12.1.0)

##### Added

###
[`v12.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1200-2024-02-03)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v11.1.0...v12.0.0)

##### Added

- `.addHelpOption()` as another way of configuring built-in help option
(\[[#&#8203;2006](https://redirect.github.com/tj/commander.js/issues/2006)])
- `.helpCommand()` for configuring built-in help command
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Fixed

- *Breaking:* use non-zero exit code when spawned executable subcommand
terminates due to a signal
(\[[#&#8203;2023](https://redirect.github.com/tj/commander.js/issues/2023)])
- *Breaking:* check `passThroughOptions` constraints when using
`.addCommand` and throw if parent command does not have
`.enablePositionalOptions()` enabled
(\[[#&#8203;1937](https://redirect.github.com/tj/commander.js/issues/1937)])

##### Changed

- *Breaking:* Commander 12 requires Node.js v18 or higher
(\[[#&#8203;2027](https://redirect.github.com/tj/commander.js/issues/2027)])
- *Breaking:* throw an error if add an option with a flag which is
already in use
(\[[#&#8203;2055](https://redirect.github.com/tj/commander.js/issues/2055)])
- *Breaking:* throw an error if add a command with name or alias which
is already in use
(\[[#&#8203;2059](https://redirect.github.com/tj/commander.js/issues/2059)])
- *Breaking:* throw error when calling `.storeOptionsAsProperties()`
after setting an option value
(\[[#&#8203;1928](https://redirect.github.com/tj/commander.js/issues/1928)])
- replace non-standard JSDoc of `@api private` with documented
`@private`
(\[[#&#8203;1949](https://redirect.github.com/tj/commander.js/issues/1949)])
- `.addHelpCommand()` now takes a Command (passing string or boolean
still works as before but deprecated)
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])
- refactor internal implementation of built-in help option
(\[[#&#8203;2006](https://redirect.github.com/tj/commander.js/issues/2006)])
- refactor internal implementation of built-in help command
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Deprecated

- `.addHelpCommand()` passing string or boolean (use `.helpCommand()` or
pass a Command)
(\[[#&#8203;2087](https://redirect.github.com/tj/commander.js/issues/2087)])

##### Removed

- *Breaking:* removed default export of a global Command instance from
CommonJS (use the named `program` export instead)
(\[[#&#8203;2017](https://redirect.github.com/tj/commander.js/issues/2017)])

##### Migration Tips

**global program**

If you are using the
[deprecated](./docs/deprecated.md#default-import-of-global-command-object)
default import of the global Command object, you need to switch to using
a named import (or create a new `Command`).

```js
// const program = require('commander');
const { program } = require('commander');
```

**option and command clashes**

A couple of configuration problems now throw an error, which will pick
up issues in existing programs:

-   adding an option which uses the same flag as a previous option
- adding a command which uses the same name or alias as a previous
command

###
[`v11.1.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1110-2023-10-13)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v11.0.0...v11.1.0)

##### Fixed

- TypeScript: update `OptionValueSource` to allow any string, to match
supported use of custom sources
(\[[#&#8203;1983](https://redirect.github.com/tj/commander.js/issues/1983)])
- TypeScript: add that `Command.version()` can also be used as getter
(\[[#&#8203;1982](https://redirect.github.com/tj/commander.js/issues/1982)])
- TypeScript: add null return type to `Commands.executableDir()`, for
when not configured
(\[[#&#8203;1965](https://redirect.github.com/tj/commander.js/issues/1965)])
- subcommands with an executable handler and only a short help flag are
now handled correctly by the parent's help command
(\[[#&#8203;1930](https://redirect.github.com/tj/commander.js/issues/1930)])

##### Added

- `registeredArguments` property on `Command` with the array of defined
`Argument` (like `Command.options` for `Option`)
(\[[#&#8203;2010](https://redirect.github.com/tj/commander.js/issues/2010)])
- TypeScript declarations for Option properties: `envVar`, `presetArg`
(\[[#&#8203;2019](https://redirect.github.com/tj/commander.js/issues/2019)])
- TypeScript declarations for Argument properties: `argChoices`,
`defaultValue`, `defaultValueDescription`
(\[[#&#8203;2019](https://redirect.github.com/tj/commander.js/issues/2019)])
- example file which shows how to configure help to display any custom
usage in the list of subcommands
(\[[#&#8203;1896](https://redirect.github.com/tj/commander.js/issues/1896)])

##### Changed

- (developer) refactor TypeScript configs for multiple use-cases, and
enable checks in JavaScript files in supporting editors
(\[[#&#8203;1969](https://redirect.github.com/tj/commander.js/issues/1969)])

##### Deprecated

- `Command._args` was private anyway, but now available as
`registeredArguments`
(\[[#&#8203;2010](https://redirect.github.com/tj/commander.js/issues/2010)])

###
[`v11.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1100-2023-06-16)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v10.0.1...v11.0.0)

##### Fixed

- help command works when help option is disabled
(\[[#&#8203;1864](https://redirect.github.com/tj/commander.js/issues/1864)])

##### Changed

- leading and trailing spaces are now ignored by the .arguments() method
(\[[#&#8203;1874](https://redirect.github.com/tj/commander.js/issues/1874)])
- refine "types" exports for ESM to follow TypeScript guidelines
(\[[#&#8203;1886](https://redirect.github.com/tj/commander.js/issues/1886)])
-   *Breaking:* Commander 11 requires Node.js v16 or higher

###
[`v10.0.1`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1001-2023-04-15)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v10.0.0...v10.0.1)

##### Added

- improvements to documentation
(\[[#&#8203;1858](https://redirect.github.com/tj/commander.js/issues/1858)],
\[[#&#8203;1859](https://redirect.github.com/tj/commander.js/issues/1859)],
\[[#&#8203;1860](https://redirect.github.com/tj/commander.js/issues/1860)])

##### Fixed

- remove unused `Option.optionFlags` property from TypeScript definition
(\[[#&#8203;1844](https://redirect.github.com/tj/commander.js/issues/1844)])

##### Changed

- assume boolean option intended if caller passes string instead of hash
to `.implies()`
(\[[#&#8203;1854](https://redirect.github.com/tj/commander.js/issues/1854)])

###
[`v10.0.0`](https://redirect.github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1000-2023-01-13)

[Compare
Source](https://redirect.github.com/tj/commander.js/compare/v9.5.0...v10.0.0)

##### Added

- wrap command description in help
(\[[#&#8203;1804](https://redirect.github.com/tj/commander.js/issues/1804)])

##### Changed

-   *Breaking:* Commander 10 requires Node.js v14 or higher

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/runtime-env/import-meta-env).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xNjcuMSIsInVwZGF0ZWRJblZlciI6IjM5LjE2Ny4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>